version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - playground-network

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - playground-network

networks:
  playground-network:
    driver: bridge
